version: '3.8'
services:
  cleaner_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cleaner_dev
    volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./dev_ws/src:/root/dev_ws/src
      - /dev:/dev
    device_cgroup_rules:
      - "c *:* rmw"
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DRIVERS=all
    network_mode: "host"
    ipc: "host"
    # privileged: true
    stdin_open: true
    tty: true
    user: "ros"

